name: Deployment

on:
  push:
    branches: [ master ]

jobs:

  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup project
        run: yarn install --frozen-lockfile

      - name: Deploy project
        run: yarn deploy
        env:
          VITE_MIRO_APP_ID: ${{ secrets.VITE_MIRO_APP_ID }}
