name: Build, lint and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup project
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Lint
        run: yarn run lint

      - name: Unit Tests
        run: yarn run test:coverage

      - name: Upload to codecov
        uses: codecov/codecov-action@v2
