name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: "test env"
        run: echo ${{ secrets.VITE_MIRO_APP_ID }}

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup project
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Unit Tests
        run: yarn run test:coverage

      - name: Upload to codecov
        uses: codecov/codecov-action@v2
